"""
Phase 0 + Phase 1: clean up the user's query, then search the web for
candidate sources via Tavily.
"""
import json
import re
from typing import Dict, List

import requests

import config
from utils import cache
from utils.llm_client import LLMError, call_nvidia_api
from utils.logger import get_logger

logger = get_logger(__name__)


def optimize_query(query: str) -> str:
    """Fixes obvious typos in the query. Uses the fast 8B model - this is a
    trivial correction task and never needed 70B-level reasoning."""
    logger.info("PHASE 0: optimizing query: %r", query)
    prompt = (
        "You are a strict query optimizer. Correct any spelling mistakes or typos in this "
        "search query. Return ONLY the exact corrected query string, nothing else - no quotes, "
        f"no intro text, no markdown.\nOriginal: '{query}'"
    )
    try:
        corrected = call_nvidia_api(prompt, max_tokens=50, temperature=0.1, model="fast", retries=1)
        corrected = corrected.strip().strip("'\"")
        if corrected and corrected.lower() != query.lower():
            logger.info("Query auto-corrected to: %r", corrected)
            return corrected
        return query
    except LLMError as e:
        logger.warning("Query optimization skipped (%s); using raw query.", e)
        return query


def _generate_sub_queries(query: str) -> List[str]:
    """
    Uses the fast LLM to expand one user query into 3 diverse sub-queries
    for better search coverage - especially useful for niche or ambiguous
    topics where a single query may miss important angles.
    Falls back to a simple heuristic list if the LLM call fails.
    """
    prompt = (
        f"Generate 3 diverse, specific web search queries for deep research on this topic: '{query}'. "
        "Queries should cover different angles (e.g. overview, current trends, examples/case studies). "
        "Return ONLY a JSON array of 3 strings, nothing else. Example: "
        '["query one", "query two", "query three"]'
    )
    try:
        raw = call_nvidia_api(prompt, max_tokens=120, temperature=0.3, model="fast", retries=1)
        # Strip markdown fences and try bracket-counted extraction to avoid
        # greedy-regex "Extra data" errors when the model emits extra lines.
        text = re.sub(r"```(?:json)?\s*", "", raw).strip()
        start = text.find("[")
        if start != -1:
            depth, in_str, esc = 0, False, False
            for i, ch in enumerate(text[start:], start):
                if esc:
                    esc = False; continue
                if ch == "\\" and in_str:
                    esc = True; continue
                if ch == '"':
                    in_str = not in_str; continue
                if in_str:
                    continue
                if ch == "[":
                    depth += 1
                elif ch == "]":
                    depth -= 1
                    if depth == 0:
                        queries = json.loads(text[start:i + 1])
                        if isinstance(queries, list):
                            sub = [str(q).strip() for q in queries if str(q).strip()][:3]
                            if sub:
                                return sub
                        break
    except Exception as e:
        logger.warning("Sub-query generation failed (%s); using fallback queries.", e)

    # Heuristic fallback: three simple angle variants
    return [
        f"{query} overview and key concepts",
        f"{query} recent developments 2024 2025",
        f"{query} examples case studies analysis",
    ]


def _tavily_search(query: str, search_depth: str, max_results: int) -> List[Dict]:
    """Fires one Tavily search and returns the results list (or [] on failure)."""
    payload = {
        "api_key": config.TAVILY_API_KEY,
        "query": query,
        "search_depth": search_depth,
        "max_results": max_results,
        "include_answer": False,
    }
    try:
        response = requests.post(config.TAVILY_URL, json=payload, timeout=config.SEARCH_TIMEOUT)
        response.raise_for_status()
        return response.json().get("results", [])
    except requests.exceptions.RequestException as e:
        logger.warning("Tavily search error for %r: %s", query, e)
        return []


def fetch_articles(query: str, max_results: int = None, search_depth: str = None) -> List[Dict]:
    """
    Phase 1: Multi-query Tavily search for broader, more robust coverage.

    Instead of a single search, we fire the primary query plus 2-3
    targeted sub-queries (generated by the LLM to cover different angles
    of the topic) and merge the results, deduplicating by URL. This
    significantly reduces shallow-research failures where a single Tavily
    query returns only a handful of closely related articles.

    Results are cached by primary query so repeated/similar topics still
    benefit from the cache (and the extra LLM+Tavily calls are skipped).
    """
    max_results = max_results or config.SEARCH_MAX_RESULTS
    search_depth = search_depth or config.SEARCH_DEPTH
    logger.info("PHASE 1: searching web for %r (depth=%s, max_results=%s)", query, search_depth, max_results)

    cache_key = cache.make_key("search_v2", query, search_depth, str(max_results))
    cached = cache.get(cache_key)
    if cached is not None:
        logger.info("Search cache hit for %r (%s results)", query, len(cached))
        return cached

    if not config.TAVILY_API_KEY:
        logger.error("TAVILY_API_KEY is not configured - cannot search.")
        return []

    # Primary query + diverse sub-queries for wider coverage
    sub_queries = _generate_sub_queries(query)
    all_queries = [query] + sub_queries
    logger.info("Running %s search queries: %s", len(all_queries), all_queries)

    # Per-query result cap: divide budget across queries, minimum 5 each
    per_query_results = max(5, max_results // len(all_queries))

    seen_urls: set = set()
    merged: List[Dict] = []

    for q in all_queries:
        results = _tavily_search(q, search_depth, per_query_results)
        for article in results:
            url = article.get("url", "")
            if url and url not in seen_urls:
                seen_urls.add(url)
                merged.append(article)

    logger.info("Fetched %s unique articles across %s queries.", len(merged), len(all_queries))

    if merged:
        cache.set(cache_key, merged)
    return merged
